### ISSUE TITLE
After long connection, it fails without clientOnClose callback

### ISSUE THREAD

**Issue by dkorkin** [shuoli84/SocketIOCocoa#13] opened 2015-02-05 08:55 UTC
I have long connection with server, and I see logs:

[EngineSocket(Optional("qZixT-p7qaxD3Uz4AACS"))][Open][Upg:0][TW:1] Sending Ping
[EngineSocket(Optional("qZixT-p7qaxD3Uz4AACS"))][Open][Upg:0][TW:1] Setting up ping and reset timeout
[EngineSocket(Optional("qZixT-p7qaxD3Uz4AACS"))][Open][Upg:0][TW:1] Enqueue packet
[EngineSocket(Optional("qZixT-p7qaxD3Uz4AACS"))][Open][Upg:0][TW:1] Flushing 1 packets
[WebsocketTransport][Open] Received text message 3

But when I have lost connection, I didn't receive   "Received text message 3" any more and clientOnClose delegate didn't call

**Comment by shuoli84** [comment] 2015-02-05 12:29
What do you mean by lost connection. Not receiving Text message 3 is expected, The problem is client close not fired?

发自我的 iPhone

**Comment by dkorkin** [comment] 2015-02-05 12:51
In this case on server - user is log out and on client side client close not fired and socket.connected = YES. This delegate method very important for us, cause we observe connection manually, some additional information:

            self.client = [[SocketIOClient alloc] initWithUri:connectionUrl query:params transports:@[@"polling", @"websocket"] autoConnect:NO reconnect:NO reconnectAttempts:0 reconnectDelay:0 reconnectDelayMax:5 timeout:10];

And on clientOnClose we add check: was it disconnected after the call [self.client close]; or not. If not, we use [self.client open];  to open new connection.

Do you have any ideas?

**Comment by shuoli84** [comment] 2015-02-05 14:01
From the code, when the underlying websocket closed, at least you should see one log:
"The transport closed unexpected". 
It should be a bug, I am trying to reproduce it.

**Comment by dkorkin** [comment] 2015-02-05 14:06
I also put some logs to  private func processRawMessage,  and
private func processResponse(response: WSResponse) -> Bool {
        if response.isFin && response.bytesLeft <= 0 {
            NSLog("processResponse - response.code \(response.code.rawValue)")

Reproducing of this bug is not easy, it can appear after 30-40 min of connection

**Comment by shuoli84** [comment] 2015-02-05 15:43
Do you mean it will happen after 30-40 minutes no matter whether the connection dropped?

**Comment by dkorkin** [comment] 2015-02-05 16:00
Sometimes it happened, sometimes not, there is no actual test case, but 
1) App come to background, then active we use the same client (open call) and it fail
2) App is active, but chat and client not in use, internet connection is active too. Then u try to send some events, but server side think that you logged out (we use ping interval 3s)

And as I notified starscream has some changed and fixes, maybe it can be the reason and we should update it?

**Comment by dkorkin** [comment] 2015-02-05 16:20
I think I found some case,  when my app become active I use [self.client open]; and when I push home button and on app event applicationDidEnterBackground calls [self.client close]; And when I try to do this couple on time one after another I such logs and client no more active
[D][EngineSocket(Optional("0PuCslhKOLy8eGUOAABH"))][Closing][Upg:0][TW:1] Enqueue packet
 [D][EngineSocket(Optional("0PuCslhKOLy8eGUOAABH"))][Closing][Upg:0][TW:1] Flushing 1 packets
 [D][EngineSocket(Optional("0PuCslhKOLy8eGUOAABH"))][Closing][Upg:0][TW:1] PACKETS [[Message][Binary: false]: 2/chat,["message",{"message":"Ghj","localId":"121A31C8C4F-491C-499A-8666-E43EC7AA08E5","toUserId":128}]]
[D][WebsocketTransport][Closing] WRITE Websocket EngineTransport --readyState Closing

after last logs no activity

**Comment by shuoli84** [comment] 2015-02-05 16:22
Thanks for the info, I just fixed another bug and looking on this now.

**Comment by dkorkin** [comment] 2015-02-05 16:33
It can cause of difference starscream.swift (612)
            while true {
                if self.outputStream == nil {
                    break
                }
                let writeBuffer = UnsafePointer<UInt8>(frame!.bytes+total)
                var len = self.outputStream!.write(writeBuffer, maxLength: offset-total)
                if len < 0 {
                    self.delegate?.websocketDidDisconnect(self.outputStream!.streamError)
                    break
                } else {
                    total += len
                }
                if total >= offset {
                    break
                }
            }

and original

            while true {
                if self.outputStream == nil {
                    break
                }
                let writeBuffer = UnsafePointer<UInt8>(frame!.bytes+total)
                var len = self.outputStream!.write(writeBuffer, maxLength: offset-total)
                if len < 0 {
                    if let disconnect = self.disconnectedBlock {
                        disconnect(self.outputStream!.streamError!)
                    }
                    self.delegate?.websocketDidDisconnect(self, error: self.outputStream!.streamError)
                    break
                } else {
                    total += len
                }
                if total >= offset {
                    break
                }
            }

at stack of calls with one is missed self.delegate?.websocketDidDisconnect(self, error: self.outputStream!.streamError)

**Comment by shuoli84** [comment] 2015-02-05 17:04
I got some clues, will try to fix it tomorrow. Thanks for all the info :)

**Comment by shuoli84** [comment] 2015-02-06 16:36
@dkorkin The bug should be fixed, now the client can be close and open, pls try the latest code.

**Comment by dkorkin** [comment] 2015-02-06 21:35
I tried last version from commit 305be792b810f91fe44346ac14617d197315b7a0 (66 commits) and it worked less stable as version b674b72f5004bb2b129d618a7b52c841e18e8285 (63 commits) The problem was reproduced (often connect and disconnect cause of it). I'll send you full logs of case, maybe it helps to understand the problem.

**Comment by shuoli84** [comment] 2015-02-07 02:03
@dkorkin yes please. I thought the bug is caused by open and close, and confirmed with a test case.

**Comment by dkorkin** [comment] 2015-02-07 11:11
@shuoli84 according to my mail and file ConnectionLogic:
applicationDidBecomeActive - [self.client open];
applicationDidEnterBackground - [self.client close];
+ timer to monitor connection
I perform sequence of open and close (10-20) by turning app to bg and going back and when app was active I emitted some events(send message) and get events after connect (get message history) full log of such operation presented in file Logs-SocketIO-Cocoa, which was attached to letter

**Comment by shuoli84** [comment] 2015-02-07 11:56
@dkorkin Didn't see the attachment. Could u pls send it again?

**Comment by shuoli84** [comment] 2015-02-07 11:59
@dkorkin I see it, from another mail.

**Comment by dkorkin** [comment] 2015-02-07 12:01
I use this email, is it right? shuoli84@gmail.com

**Comment by shuoli84** [comment] 2015-02-07 13:19
Thanks for the log, I found the bug.

**Closed** 2015-02-07 13:21 UTC
